M48
; DRILL file {KiCad 9.0.0} date 2025-03-07T14:57:58+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-07T14:57:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X121.6Y-106.31
X132.6Y-106.31
T2
X174.83Y-207.3
T3
X70.9Y-128.82
X70.9Y-185.82
X180.9Y-128.82
X180.9Y-185.82
M30
